### ISSUE TITLE
Alt conversion guide?

### ISSUE THREAD

**Issue by n8stowell82** [koliseoapi/alt-ng#1]
Hey guys! thanks for picking up the torch and running with this project.  Our company has been running into several issues with alt recently.  We ran across your project and I took a stab at switching from alt to alt-ng.  I ran into several issues, but most were b/c I was trying to do things the "alt" way and not the "alt-ng" way.

Do you guys have any documentation explaining the easiest way to convert from alt to alt-ng?  Thanks!

**Comment by icoloma** [comment]
Hey! Thanks for inaugurating the issue tracker! :)

We are planning to add a page about how to bootstrap Stores with initial data (as it may not be obvious to everybody). It probably makes sense to add all the differences with Alt in a single place as well. Can you recall what were your "a-ha" moments while migrating? We'd like to include more points of view if possible.

**Comment by icoloma** [comment]
We have added a [Migration Guide](http://alt-ng.koliseo.com/doc/migrating-from-alt) (source [here](https://github.com/koliseoapi/alt-ng/blob/gh-pages/doc/migrating-from-alt.md)), please reopen or send a PR if you are missing stuff. Thanks!

**Comment by n8stowell82** [comment]
Hey, thank you so much for making that guide!  Sorry I didn't get a chance to respond earlier.  I haven't had a chance to thoroughly read the new guide (on my list to do this weekend!) but I think I am most hung up on the actions.  At the moment every time I try to call an action on a store I get an error something like 

> _actions.AppAction.awesomeAction is not a function

I assume I just don't have everything quite wired up correctly.  I will work through your guide over the weekend, and if I am still having issues I will post here with more questions.  Thank you so much for moving this project forward
