### ISSUE TITLE
Reconsider the proper way of notifying Promises

### ISSUE THREAD

**Issue by icoloma** [koliseoapi/alt-ng#2]
In its current form, an action that returns a Promise will notify twice:

* `{payload:null,loading:true}` when the Promise has been returned from the action, but not yet resolved
* `{payload:something,loading:false}` or `{payload:null,error: something,loading:false}` depending if the Promise was resolved or rejected.

The problem is that there is no way of communicating more information from the action. If I wanted to use a single action for multiple things, and include information when dispatching a load, that is not possible. For example, an action could return a `PagedValue` and use `PagedValue.url` as part of the payload, but for `loading` and `error` no extra information could be provided.

The most likely solution would be to provide methods inside an action to dispatch new actions, and remove the notification that exists actually for `loading` and `error` states. Such an action could look something like this:

```js
alt.createActions('PagedActions', {

  fetchPage(url) {
     this.dispatch({ url, loading: true });
     return MyApi.fetch(url).catch((e) => this.dispatch({ error });
  }

});
```

Any ideas?

**Comment by ccoloma** [comment]
SGTM if we are talking about stateless actions (like the `fetchPage` example you mention)

**Comment by icoloma** [comment]
This issue is implemented, pending documentation.
